id: 'd829e8ec-d42d-4473-737b-08dd7ccec69f'
name: 'C3-X-DB-FI'
description: 'This is my eLearning Project with the Databricks Stage Filegenerator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Spark.Databricks.File'
  version: '1.9.0'
sourceSystems:
  - id: '8d636446-4de2-47ac-8213-d073cd15031c'
    name: 'Adventure Works'
    description: 'This is the source system for the Adventure Works parquet file'
    sourceSystemTypeId: 'c5e55725-184f-4c60-a22d-70cb5d6fe513'
